os: linux
compiler: gcc

env:
  global:
    - GIT_NAME: "FreeMiNT Project"
    - GIT_EMAIL: "freemint-list@mail.atariforge.org"
    - GIT_REPOSITORY: "git@github.com:freemint/tos.hyp.git"

before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_REPO_SLUG}" = "freemint/tos.hyp" ];
    then
      openssl aes-256-cbc -K $encrypted_e5cfea0e0f2e_key -iv $encrypted_e5cfea0e0f2e_iv -in .travis/deploy-key.enc -out .travis/deploy-key -d
    fi

before_script:
  - svn co "svn://udo-open-source.org/UDO/trunk" "/tmp/udo"
  - cd "/tmp/udo/Source" && make -f Makefile.linux
  - export PATH=$PATH:"/tmp/udo/Source"
  - cd -
  
  - cd "/tmp"
  - wget "http://tho-otto.de/download/hcp-0.9.9-linux.tar.bz2"
  - tar xjf hcp-0.9.9-linux.tar.bz2
  - export PATH=$PATH:"/tmp/hcp-0.9.9/bin"
  - cd -

script:
  - mkdir -p "gh-pages/de/bilder" "gh-pages/en/bilder" "gh-pages/archives"
  - cp -r "bilder/gif" "gh-pages/de/bilder"
  - cp -r "bilder/gif" "gh-pages/en/bilder"
  - cp "html/tos_hyp.gif" "gh-pages"
  - udo --html -o "$PWD/gh-pages/index.html" "$PWD/html/tos_hyp.u"
  - udo --html --tree -o "$PWD/gh-pages/de/index.html" "$PWD/tos_hyp.u"
  - udo --stg -o "$PWD/gh-pages/archives/tos_hyp_de.stg" "$PWD/tos_hyp.u" || true
  - hcp -o "gh-pages/archives/tos_hyp_de.hyp" "gh-pages/archives/tos_hyp_de.stg" || true

  - cd "gh-pages/archives"
  - mv "tos_hyp_de.hyp" "tos_hyp.hyp"
  - mv "tos_hyp_de.ref" "tos_hyp.ref"
  - zip -9 tos_hyp_de.zip "tos_hyp.hyp" "tos_hyp.ref"
  - rm -f *.stg *.uhs *.uls *.hyp *.ref
  - cd -

  - sed -e 's/^#!language english/!language english/;' -e 's/^!language german/#!language german/;' config.u > config.u.tmp && mv config.u.tmp config.u
  - udo --html --tree -o "$PWD/gh-pages/en/index.html" "$PWD/tos_hyp.u"
  - udo --stg -o "$PWD/gh-pages/archives/tos_hyp_en.stg" "$PWD/tos_hyp.u" || true
  - hcp -o "gh-pages/archives/tos_hyp_en.hyp" "gh-pages/archives/tos_hyp_en.stg" || true
  
  - cd "gh-pages/archives"
  - mv "tos_hyp_en.hyp" "tos_hyp.hyp"
  - mv "tos_hyp_en.ref" "tos_hyp.ref"
  - zip -9 tos_hyp_en.zip "tos_hyp.hyp" "tos_hyp.ref"
  - rm -f *.stg *.uhs *.uls *.hyp *.ref
  - cd -
  
after_success:
  # publish only on master
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_REPO_SLUG}" = "freemint/tos.hyp" ];
    then
      eval "$(ssh-agent -s)";
      chmod 600 ".travis/deploy-key";
      ssh-add ".travis/deploy-key"; 
      cd gh-pages && git init && git config user.name "${GIT_NAME}" && git config user.email "${GIT_EMAIL}" &&
      git add . && git commit -m "Publish ${TRAVIS_COMMIT}" && git push --force "${GIT_REPOSITORY}" master:gh-pages;
    fi
